//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Batman.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Batman.Resources.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ბეტმენიე.
        /// </summary>
        public static string BatmanName {
            get {
                return ResourceManager.GetString("BatmanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batman არის გმირი, და დაფრინავს ცაში, ებრძვის ბოროტებს, მხოლოდ გოთემში.
        /// </summary>
        public static string BatmanStory {
            get {
                return ResourceManager.GetString("BatmanStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გაიგე მეტი.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1996-ის ბეტმენი.
        /// </summary>
        public static string Title1966 {
            get {
                return ResourceManager.GetString("Title1966", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batman-ის აიდი.
        /// </summary>
        public static string TitleCard {
            get {
                return ResourceManager.GetString("TitleCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ლ&apos;ეგო.
        /// </summary>
        public static string TitleLego {
            get {
                return ResourceManager.GetString("TitleLego", resourceCulture);
            }
        }
    }
}
